# Generated by Django 5.0.1 on 2024-01-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
